#!/bin/bash

if [ ! -d /etc/X11/xorg.conf.d ]; then
sudo mkdir -p /etc/X11/xorg.conf.d
fi
sudo cp ./usr/tft35a-overlay.dtb /boot/overlays/
sudo cp ./usr/tft35a-overlay.dtb /boot/overlays/tft35a.dtbo

sudo echo "hdmi_force_hotplug=1" >> ./boot/firmware/config.txt
sudo echo "dtparam=i2c_arm=on" >> ./boot/firmware/config.txt
sudo echo "dtparam=spi=on" >> ./boot/firmware/config.txt
sudo echo "enable_uart=1" >> ./boot/firmware/config.txt
sudo echo "dtoverlay=tft35a" >> ./boot/firmware/config.txt
sudo echo "hdmi_group=2" >> ./boot/firmware/config.txt
sudo echo "hdmi_mode=1" >> ./boot/firmware/config.txt
sudo echo "hdmi_mode=87" >> ./boot/firmware/config.txt
sudo echo "hdmi_cvt 480 320 60 6 0 0 0" >> ./boot/firmware/config.txt
sudo echo "hdmi_drive=2" >> ./boot/firmware/config.txt


sudo cp -rf ./usr/99-calibration.conf-35-90  /etc/X11/xorg.conf.d/99-calibration.conf
sudo cp -rf /usr/share/X11/xorg.conf.d/10-evdev.conf /usr/share/X11/xorg.conf.d/45-evdev.conf

sudo cp ./usr/inittab /etc/
sudo cp -rf ./etc/rc.local /etc/

sudo apt-get install cmake libraspberrypi-dev -y
sudo apt-get install xserver-xorg-input-evdev -y
sudo apt-get install xserver-xorg-input-evdev xinput-calibrator -y

sudo mkdir ./rpi-fbcp/build
cd ./rpi-fbcp/build/
sudo cmake ..
sudo make
sudo install fbcp /usr/local/bin/fbcp
cd - > /dev/null


sudo sync
sudo sync
sleep 1

sudo systemctl disable glamor-test.service
sudo cat /usr/share/X11/xorg.conf.d/20-noglamor.conf | sed -e '/EndSection/i Driver "fbdev"' > /usr/share/X11/xorg.conf.d/21-noglamor.conf
sudo rm /usr/share/X11/xorg.conf.d/20-noglamor.conf
sudo systemctl restart lightdm

echo "reboot now"
sudo reboot
